### ISSUE TITLE
No such file or directory: 'test_requirements.txt'

### ISSUE THREAD

**Issue by RiceeeChang** [abenassi/Google-Search-API#29]
i use python3.6 and win10

when i install with pip , occur this error

C:\Users\User\AppData\Local\Programs\Python\Python36\Scripts>pip install  Google-Search-API
Collecting Google-Search-API
  Using cached Google-Search-API-1.1.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-build-e584nunp\Google-Search-API\setup.py", line 15, in <module>
        with open("test_requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'test_requirements.txt'

**Comment by ThaWeatherman** [comment]
I noticed a bunch of prints without parens, so I think this is only py2-compatible

**Comment by saitiku** [comment]
when would it be possible to get python3 support?

**Comment by master98ofu** [comment]
I mean, there is a package called py2to3 it might work I haven't tried

**Comment by jadolg** [comment]
I'm getting the same error on Ubuntu 16.04 using python 3.5 
`Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yikuk4jt/Google-Search-API/setup.py", line 15, in <module>
        with open("test_requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'test_requirements.txt'`

**Comment by terencezl** [comment]
If you install with `pip install git+https://github.com/abenassi/Google-Search-API/` there is no such problem.

**Comment by mndhkr** [comment]
is pip install git+https://github.com/abenassi/Google-Search-API/ issuable on heroku?

**Comment by DaandenHartog** [comment]
It is, but instead of `module_name==module_version` you just paste the link.

This is what my requirements.txt looks like
```praw==5.2.0
prawcore==0.12.0
requests==2.18.1
beautifulsoup4==4.6.0
git+https://github.com/abenassi/Google-Search-API/
