### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by Filiprb** [abenassi/Google-Search-API#48]
Hello,

I'm having trouble installing this package. I use the comand: 

`pip install Google-Search-API`

but get the following error

"Command "python setup.py egg_info" failed with error code 1 in..."

I have tried 

`pip install --upgrade setuptools`
`pip install ez_setup`
`easy_install -U setuptools`

without success. Can anyone help me on this issue?

**Comment by scoocs** [comment]
I have same issue

**Comment by mhamedLmarbouh** [comment]
the same over here

**Comment by Detoy** [comment]
Same issue. It said that the package does not support this version of Python when I tried to install from the .whl file. There has to be a workaround I think.

**Comment by abhishtagatya** [comment]
use `sudo` for root access (If your on UNIX / Linux)

`sudo pip install Google-Search-API`

**Comment by stella-lu** [comment]
I'm having the same problem and even after trying:
`sudo pip install Google-Search-API
sudo -H pip install Google-Search-API`
I'm getting the same error message. 
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-j1q0s471/Google-Search-API/

**Comment by RealistikDash** [comment]
just clone the project, copy to your project directory and add `from google import google` to your project. Just a temporary workaround.

**Comment by stella-lu** [comment]
From the readme, how would I import the package from the Google-Search API folder? I've tried:
```
import os
os.chdir("/Users/Name/project-folder-name/Google-Search-API/")
from google import google
```
which results in "ModuleNotFoundError: No module named 'google'"

**Comment by JuaniFilardo** [comment]
@stella-lu, I reckon that a better option than `os.chdir()` might be:
```
import sys
sys.path.append('/home/your_user/Projects/Google-Search-API')
from google import google
```
That should do. Try it and let me know if that helps :)

**Comment by stella-lu** [comment]
@JuaniFilardo 
I tried:
```
import sys
sys.path.append('/Users/Name/Project/Google-Search-API')
from google import google
```
and I get this error:
```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from google import google
  File "/Users/Cactus/wiki-word-frequency/Google-Search-API/google/__init__.py", line 2, in <module>
    from .modules import calculator, currency, images, utils
  File "/Users/Cactus/wiki-word-frequency/Google-Search-API/google/modules/__init__.py", line 2, in <module>
    from . import calculator
  File "/Users/Cactus/wiki-word-frequency/Google-Search-API/google/modules/calculator.py", line 4, in <module>
    from unidecode import unidecode
ModuleNotFoundError: No module named 'unidecode'
```

**Comment by JuaniFilardo** [comment]
That's because you didn't install the packages needed. First run `pip install -r requirements.txt` (or install each module manually till you don't get any errors).

**Comment by stella-lu** [comment]
@JuaniFilardo Thank you! I'm a little new to all of this, but that worked.

**Comment by anisayari** [comment]
I am not quite sure that this issue is referenced to #55 ... 
By the way I got the same issue trying a first installation .
```
File ".\google\__init__.py", line 1, in <module>
        from modules import calculator, currency, images, utils
    ModuleNotFoundError: No module named 'modules'
 ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
```

**Comment by asharpie** [comment]
@JuaniFilardo I ran your code yet i still get a 
`Traceback (most recent call last):
  File "testing.py", line 3, in <module>
    from google import google
ImportError: cannot import name 'google'`
Is there anything i could do?

**Comment by JuaniFilardo** [comment]
@asharpie How did you install and how are you importing the module? I mean, did you appended the path or something?

**Comment by asharpie** [comment]
Nvm i fixed it by just adding the directory to my project and importing it from there @JuaniFilardo Ty though!

**Comment by asharpie** [comment]
Wait i was wrong, i was importing the google directory and not the google.py, idk what to do lol. @JuaniFilardo

**Comment by asharpie** [comment]
And I did append the path etc this is my code:

`sys.path.append('path/to/directory/Google-Search-API')
from google import google`
but then once run i get:

`File "testing.py", line 3, in <module>
    from google import google
ImportError: cannot import name 'google'`
@JuaniFilardo

**Comment by harsh085** [comment]
i tried different solutions but it always show error-

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'google'
```

please help me .

**Comment by ahammad52003** [comment]
I got the following error to install from here.

Error:
Command "python setup.py egg_info" failed with error code 1 in C:\Users\parul\AppData\Local\Temp\pip-req-build-a580mht0\

Note: I updated pip, setuptools & ez_setup

could you please help me?

**Comment by ahammad52003** [comment]
> I got the following error to install from here.
> 
> Error:
> ModuleNotFoundError: No module named 'unidecode'
> ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\parul\AppData\Local\Temp\pip-req-build-a580mht0\
> 
> Note: I updated pip, setuptools & ez_setup
> 
> could you please help me?
-----------------------------------------------------------------
I fixed it. 

Just clone it to C:\Users\userName\Documents\Google-Search-API
1. open command Prompt and type- cd C:\Users\userName\Documents\Google-Search-API
2. pip install -r requirements.txt -t C:\Users\userName\AppData\Local\Programs\Python\Python36\Scripts
3. python setup.py install
