### ISSUE TITLE
can't install the library by pip

### ISSUE THREAD

**Issue by P-Alban** [abenassi/Google-Search-API#62]
I have this issue:

```
λ pip install Google-Search-API
Collecting Google-Search-API
  Downloading https://files.pythonhosted.org/packages/73/38/eab35d4db8efd12256d30963498afe5210128d3fd221332360de9fc11614/Google-Search-API-1.1.13.tar.gz
    Complete output from command python setup.py egg_info:
    c:\users\alban\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\version.py:1: UserWarning: Module google was already imported from None, but c:\users\alban\appdata\local\temp\pip-install-mn1ginnd\google-search-api is being added to sys.path
      import pkg_resources
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\alban\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\__init__.py", line 12, in <module>
        import setuptools.version
      File "c:\users\alban\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\version.py", line 1, in <module>
        import pkg_resources
      File "c:\users\alban\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3088, in <module>
        @_call_aside
      File "c:\users\alban\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3072, in _call_aside
        f(*args, **kwargs)
      File "c:\users\alban\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3116, in _initialize_master_working_set
        for dist in working_set
      File "c:\users\alban\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3116, in <genexpr>
        for dist in working_set
      File "c:\users\alban\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2639, in activate
        declare_namespace(pkg)
      File "c:\users\alban\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2176, in declare_namespace
        _handle_ns(packageName, path_item)
      File "c:\users\alban\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2111, in _handle_ns

        loader.load_module(packageName)
      File ".\google\__init__.py", line 1, in <module>
        from modules import calculator, currency, images, utils
    ModuleNotFoundError: No module named 'module
```

**Comment by agabeyalioglu** [comment]
i have the same issue

**Comment by antoncoding** [comment]
I got this Error Message:
`Collecting Google-Search-API
  Downloading https://files.pythonhosted.org/packages/73/38/eab35d4db8efd12256d30963498afe5210128d3fd221332360de9fc11614/Google-Search-API-1.1.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c4h9m6cy/Google-Search-API/setup.py", line 15, in <module>
        with open("test_requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'test_requirements.txt'
`

**Comment by ahmchua** [comment]
I got this error message: 

<img width="566" alt="screen shot 2018-08-06 at 6 16 55 pm" src="https://user-images.githubusercontent.com/16998026/43748545-fa199f7e-99a4-11e8-86d7-e3ccd00ba3da.png">

**Comment by SlashScreen** [comment]
I also got ahmchua's message.

**Comment by tristaneljed** [comment]
I guess this library is not working anymore, I got the same issue, and I can see it's failing Travis CI built.

**Comment by tristaneljed** [comment]
It works now, you have to download the requirements.txt first, then:
`pip install -r requirements.txt`
Then:
`pip install git+https://github.com/abenassi/Google-Search-API
`
and you can directly do:
`from google import google
`

**Comment by srdg** [comment]
I tried to install the packages one by one from `requirements.txt` without downloading and it still failed. It turns out the version of selenium I have installed is `3.11.01 and they need versions `<3.0.0` - in my opinion, they really should update the dependencies and mention to install the dependencies separately first in the README.

**Comment by ianchute** [comment]
Here is what installed it for me:

```
wget https://raw.githubusercontent.com/abenassi/Google-Search-API/master/requirements.txt
pip install -r requirements.txt
pip install git+https://github.com/abenassi/Google-Search-API
```

**Comment by divy-work** [comment]
Yeah @ianchute 's answer worked well for me.
