### ISSUE TITLE
Error 503 CaptchaRedirect

### ISSUE THREAD

**Issue by Anu-cool-007** [abenassi/Google-Search-API#63]
`HTTP Error 503: Service Unavailable
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\modules\utils.py", line 432, in get_html
    html = urllib.request.urlopen(request).read()
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 564, in error
    result = self._call_chain(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
/  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 756, in http_error_302
 Googling and searching Wikipedia    return self.parent.open(new, timeout=req.timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "something.py", line 326, in <module>
    function()
  File "something.py", line 287, in get_points_sample
    x, y= google_wiki(a, b, c)
  File "something.py", line 253, in google_wiki
    search_wiki = google.search(o, num_pages)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\modules\standard_search.py", line 69, in search
    html = get_html(url)
  File "C:\ProgramData\Anaconda3\lib\site-packages\google\modules\utils.py", line 437, in get_html
    if e.code == 503 and 'CaptchaRedirect' in e.read():
TypeError: a bytes-like object is required, not 'str'`

**Comment by tangxiangru** [comment]
how to solve it?
