### ISSUE TITLE
Cannot install via pip or pip3 : No module named 'unidecode'

### ISSUE THREAD

**Issue by srdg** [abenassi/Google-Search-API#67]
I tried to install the package via `pip3` and ran into error. Printing the complete error stack below :
```
$ pip3 install git+https://github.com/abenassi/Google-Search-API
Collecting git+https://github.com/abenassi/Google-Search-API
  Cloning https://github.com/abenassi/Google-Search-API to /tmp/pip-b3gqvjmb-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 11, in <module>
        from setuptools.extern.six.moves import filterfalse, map
      File "/usr/lib/python3/dist-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2046, in _handle_ns
        loader.load_module(packageName)
      File "./google/__init__.py", line 2, in <module>
        from .modules import calculator, currency, images, utils
      File "./google/modules/__init__.py", line 2, in <module>
        from . import calculator
      File "./google/modules/calculator.py", line 4, in <module>
        from unidecode import unidecode
    ImportError: No module named 'unidecode'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-b3gqvjmb-build/

```

Any help?

**Comment by MJJBennett** [comment]
Also getting this error. I installed on Windows the other day with no issue and am now trying to install the package on WSL (Ubuntu). What OS were you using, @srdg ?

**Comment by MJJBennett** [comment]
@srdg Looks like it's some sort of issue with the requirements. You'll need to manually `pip install` each dependency.

**Comment by MJJBennett** [comment]
@srdg Sorry for the late reply. Not sure if you have the library working yet, or if you went with a different workaround. 

The package requirements do say that it wants a lower version of Selenium. I would recommend trying out just making a virtual environment with Python 3.6.5 and installing the requirements exactly as listed. If that doesn't work, then I'm not really sure what else could be done. If it does, then I guess it's a workaround until the package is updated for newer releases?

**Comment by AmoghM** [comment]
@srdg I had the same problem. This is how I circumvented it.
1. Clone the repo
2. Go to the cloned repo
3. `pip install -r requirements.txt`
4. `pip install git+https://github.com/abenassi/Google-Search-API`

It will install then.

**Comment by ashwin5912** [comment]
Collecting git+https://github.com/abenassi/Google-Search-API
  Cloning https://github.com/abenassi/Google-Search-API to c:\users\shubha~1\appdata\local\temp\pip-r77q3eyw-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\runpy.py", line 183, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\runpy.py", line 142, in _get_module_details
        return _get_module_details(pkg_main_name, error)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\runpy.py", line 109, in _get_module_details
        __import__(pkg_name)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\__init__.py", line 26, in <module>
        from pip.utils import get_installed_distributions, get_prog
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 27, in <module>
        from pip._vendor import pkg_resources
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3018, in <module>
        @_call_aside
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3004, in _call_aside
        f(*args, **kwargs)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3046, in _initialize_master_working_set
        dist.activate(replace=False)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2578, in activate
        declare_namespace(pkg)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2152, in declare_namespace
        _handle_ns(packageName, path_item)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2092, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2121, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    Traceback (most recent call last):
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\users\\shubham 2\\appdata\\local\\programs\\python\\python36\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\SHUBHA~1\\AppData\\Local\\Temp\\tmpjspi4jz6', '--quiet', 'nose>=1.0']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SHUBHA~1\AppData\Local\Temp\pip-r77q3eyw-build\setup.py", line 47, in <module>
        tests_require=test_requirements
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\setuptools\dist.py", line 698, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 783, in resolve
        replace_conflicting=replace_conflicting
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 1078, in obtain
        return installer(requirement)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\setuptools\dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['c:\\users\\shubham 2\\appdata\\local\\programs\\python\\python36\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\SHUBHA~1\\AppData\\Local\\Temp\\tmpjspi4jz6', '--quiet', 'nose>=1.0']' returned non-zero exit status 1.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\SHUBHA~1\AppData\Local\Temp\pip-r77q3eyw-build\
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by ashwin5912** [comment]
$ pip3 install git+https://github.com/abenassi/Google-Search-API
Collecting git+https://github.com/abenassi/Google-Search-API
  Cloning https://github.com/abenassi/Google-Search-API to c:\users\shubha~1\appdata\local\temp\pip-r77q3eyw-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\runpy.py", line 183, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\runpy.py", line 142, in _get_module_details
        return _get_module_details(pkg_main_name, error)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\runpy.py", line 109, in _get_module_details
        __import__(pkg_name)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\__init__.py", line 26, in <module>
        from pip.utils import get_installed_distributions, get_prog
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 27, in <module>
        from pip._vendor import pkg_resources
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3018, in <module>
        @_call_aside
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3004, in _call_aside
        f(*args, **kwargs)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3046, in _initialize_master_working_set
        dist.activate(replace=False)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2578, in activate
        declare_namespace(pkg)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2152, in declare_namespace
        _handle_ns(packageName, path_item)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2092, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2121, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    Traceback (most recent call last):
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\users\\shubham 2\\appdata\\local\\programs\\python\\python36\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\SHUBHA~1\\AppData\\Local\\Temp\\tmpjspi4jz6', '--quiet', 'nose>=1.0']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SHUBHA~1\AppData\Local\Temp\pip-r77q3eyw-build\setup.py", line 47, in <module>
        tests_require=test_requirements
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\setuptools\__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\setuptools\dist.py", line 698, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 783, in resolve
        replace_conflicting=replace_conflicting
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 1078, in obtain
        return installer(requirement)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\setuptools\dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "c:\users\shubham 2\appdata\local\programs\python\python36\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['c:\\users\\shubham 2\\appdata\\local\\programs\\python\\python36\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\SHUBHA~1\\AppData\\Local\\Temp\\tmpjspi4jz6', '--quiet', 'nose>=1.0']' returned non-zero exit status 1.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\SHUBHA~1\AppData\Local\Temp\pip-r77q3eyw-build\
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\SHUBHAM 2\Desktop\Google-Search-API>
