### ISSUE TITLE
Fake User Agent Issues

### ISSUE THREAD

**Issue by SecJesus** [abenassi/Google-Search-API#80]
Hello,

Thank you for creating such a straight forward module for using Google's search. Im using Python2.7 and when trying a simple google.search(), I received this error

FakeUserAgentError: Can not load data from cache server

the UserAgent() call is in utils.py at line 432. I had to comment this out and just add a Mozilla string for the header variable and it worked. I am guessing there is some issue from the Fake User agent module.

**Comment by leonv024** [comment]
Got the same issue on Mac, but works fine on Windows.

`Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11`

**Comment by qysnn** [comment]
Same issue on Windows 10 
```
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "C:\ProgramData\Anaconda3\lib\site-packages\fake_useragent\utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
```
