### ISSUE TITLE
fake-useragent [ERROR]

### ISSUE THREAD

**Issue by cumulus13** [abenassi/Google-Search-API#97]
>> from googleapi import google
    >> num_page = 3
    >> result = google.search("Bash split string", num_page)
    Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
    Traceback (most recent call last):
      File "/opt/google-search/lib/python3.7/site-packages/fake_useragent/utils.py", line 154, in load
        for item in get_browsers(verify_ssl=verify_ssl):
      File "/opt/google-search/lib/python3.7/site-packages/fake_useragent/utils.py", line 99, in get_browsers
        html = html.split('<table class="w3-table-all notranslate">')[1]
    IndexError: list index out of range

**Comment by Elfsong** [comment]
Same error.

**Comment by shreygupta2809** [comment]
**Fixed this**
In the _**fake_useragent**_ library which is installed as a dependency in requirements.txt, update the [utils.py](https://github.com/hellysmile/fake-useragent/blob/master/fake_useragent/utils.py) file. 

**Edit 1**
Update Line 99 in utils.py to `html = html.split('<table class="ws-table-all notranslate">')[1]`

**Edit 2**
Update Line 129 in utils.py to `pattern = r'<li><a href=[^>]+>(.+?)</a></li>'`

This should get it working hopefully
